name = "hugo-edelweiss"
license = ""
licenselink = ""
description = ""
homepage = ""
demosite = ""
tags = [
    "archive",
    "blog",
    "dark",
    "landing",
    "light",
    "minimal",
    "multilingual",
    "personal",
    "responsive"
    ]
features = [
    "accessibility",
    "breadcrumbs",
    "mastodon comments",
    ]
min_version = "0.135.0"

[author]
    name = "Foxx"
    homepage = "https://foxx.ink"